fullname: Didactic Coq
shortname: didcoq
branch: main
organization: motrellin

action: true
action_appendix: |2-
            before_install: |-
              startGroup "Print opam config"
                opam config list; opam repo list; opam list
              endGroup

              startGroup "Build _CoqProject"
                sudo chown -R coq:coq .
                make _CoqProject
              endGroup
            after_script: |-
              make coqdoc
              mkdir public
              cp -r html public/docs
              cp resources/index.md public/index.md
        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            name: html-output
            path: public
        - name: Revert Coq user permissions
          # to avoid a warning at cleanup time
          if: ${{ always() }}
          run: sudo chown -R 1001:116 .
    deploy:
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      runs-on: ubuntu-latest
      needs: build
      permissions:
        contents: write

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Download artifact
          uses: actions/download-artifact@v4
          with:
            name: html-output
            path: ./out

        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v4
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./out
            publish_branch: gh-pages
            enable_jekyll: true

community: false
coqdoc: true
submodule: true #At least for coqdocjs
synopsis: tba
description: |
  tba

#chat:

authors:
  - name: Max Ole Elliger
    initial: true
    email: ole.elliger@fau.de
maintainers:
  - name: Max Ole Elliger
    nickname: motrellin

license:
  fullname: MIT License
  identifier: MIT

supported_coq_versions:
  text: Developed for 8.19.0
  opam: '{ "8.19" }'

#namespace: CoMoTemplTest

#dependencies:
  #- description: Coq Equations
    #opam:
      #name: coq-equations

namespace: DidCoq

make_target: all

documentation: |-
  ## Documentation
  tba.

#index_documentation:

coqdoc_index: ./docs/toc.html

opam-file-maintainer: ole.elliger@fau.de

tested_coq_opam_versions:
  - version: '8.19'
